development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dnsdb_dev
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dnsdb_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dnsdb
  pool: 5
  username: dnsdb
  password: XXX
  socket: /var/run/mysqld/mysqld.sock
